version: "3"
services:
  proxy:
    container_name: proxy
    image: "nginx:alpine"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx:/etc/nginx:ro"
  webauthn:
    container_name: webauthn
    build: .
    image: abrevett/webauthn-demo
    restart: unless-stopped
    ports: 
      - "8080:8080"
    environment:
      NAME: World
  mongodb:
    container_name: mongodb
    image: "mongo:5-focal"
    restart: unless-stopped
    volumes:
      - "./db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test123
